[BEGIN]
  Version=1
[END]
[BEGIN]
  ObjTp=FSgntr
  Sgntr=UserSPlus
  RelVrs=1
  IntStrVrs=1
  SPlusVrs=4.06.00
  CrossCplrVrs=1.3
[END]
[BEGIN]
  ObjTp=Hd
  Cmn1=Analog to Serial String\\\\Summary:\\Take a value and output the||1
  Cmn2=ASCII string representation of the value.\\The module takes a few||1
  Cmn3=additional inputs allowing the output to be formatted\\as either||1
  Cmn4=a decimal or hex value with/without zero padding.\\\\Inputs:\\Analog\\
  Cmn5=||4value    -  The value to convert to string representation\\\\
  Cmn6=Outputs:\\String\\    out$	 -  The resulting output.\\\\Parameters:
  Cmn7=\\Integer\\	base	 -  Specify the number base for the value (Hex||1
  Cmn8=or Dec)\\	format	 -	Specify zero padding, fixed width or no special||1
  Cmn9=formatting. \\	length   -  The length of the output string.  Only||1
  Cmn10=relevant for zero padded or fixed values.\\                If the||1
  Cmn11=output string exceeds "size" characters when zero padding is\\||2
  Cmn12=||>requested, "#trunc#" will be output.\\	point	 -	Only||1
  Cmn13=valid for Decimal mode. The number of digits after the decimal point\\
  Cmn14=				Valid values are 0 (no decimal point) up to "size".\\\\String\\
  Cmn15=||4prepend$ -  Text to prepend to the output.\\    append$  -||2
  Cmn16=Text to append to the output.
[END]
[BEGIN]
  ObjTp=Symbol
  Exclusions=1,19,20,21,88,89,167,168,179,213,214,215,216,217,225,226,248,249,266,267,310,362,378,380,405,407,408,409,478,522,537,554,586,590,611,624,718,756,767,830,841,842,854,883,955,1032,1062,1079,1128,1129,1134,1140,1157,1158,1195,1199,1220,1221,1222,1223,1299,1348,1349,1439,1472,1473,1499,1746,1803,1975,2229,2354,2514,2523,2532,2706,2707,3235,3236,3427,3454,3567,3568,3601,3602,3708,3902,3903,3912,3918,3925,3926,4206,4207,
  Exclusions_CDS=5
  Inclusions_CDS=6,7
  Name=Analog to Serial String v2 (Ultamation)
  SmplCName=Ultamation Analog to Serial String v2.usp
  Code=1
  SysRev5=4.000
  SMWRev=2.02.05
  InputList2Cue1=value
  InputList2SigType1=Analog
  OutputList2Cue1=out$
  OutputList2SigType1=Serial
  ParamCue1=[Reference Name]
  ParamCue2=base,0d,1d
  ParamSigType2=List
  ParamCue3=format,0d,1d,2d
  ParamSigType3=List
  ParamCue4=length
  ParamSigType4=Constant
  ParamCue5=point
  ParamSigType5=Constant
  ParamCue6=prepend$
  ParamSigType6=String
  ParamCue7=append$
  ParamSigType7=String
  MinVariableInputs=0
  MaxVariableInputs=0
  MinVariableInputsList2=1
  MaxVariableInputsList2=1
  MinVariableOutputs=0
  MaxVariableOutputs=0
  MinVariableOutputsList2=1
  MaxVariableOutputsList2=1
  MinVariableParams=6
  MaxVariableParams=6
  Expand=expand_separately
  Expand2=expand_separately
  ProgramTree=Logic
  SymbolTree=10
  Hint=Simplify Analog to Serial conversions
  PdfHelp=
  HelpID= 
  Render=4
  Smpl-C=16
  CompilerCode=-48
  CompilerParamCode=27
  CompilerParamCode5=14
  NumFixedParams=1
  Pp1=1
  Pp2=2
  Pp3=3
  Pp4=4
  Pp5=5
  Pp6=6
  Pp7=7
  MPp=7
  NVStorage=10
  ParamSigType1=String
  SmplCInputCue1=o#
  SmplCOutputCue1=i#
  SmplCInputList2Cue1=an#
  SmplCOutputList2Cue1=ai#
  SPlus2CompiledName=S2_Ultamation_Analog_to_Serial_String_v2
  SymJam=NonExclusive
  FileName=Ultamation Analog to Serial String v2.ush
  SIMPLPlusModuleEncoding=0
[END]
[BEGIN]
  ObjTp=Dp
  H=1
  Tp=1
  NoS=False
[END]
[BEGIN]
  ObjTp=Dp
  H=2
  Tp=1
  SD=The base for conversion of value
  HD=True
  DV=0d
  Sgn=0
  Lng=False
  NF=1
  NoS=True
  DNF=1
  VVS=2
  VN=2
  Val1=0d
  Lbl1=Decimal
  Val2=1d
  Lbl2=Hex
[END]
[BEGIN]
  ObjTp=Dp
  H=3
  Tp=1
  SD=How to format the output
  HD=True
  DV=0d
  Sgn=0
  Lng=False
  NF=1
  NoS=True
  DNF=1
  VVS=2
  VN=3
  Val1=0d
  Lbl1=None
  Val2=1d
  Lbl2=Fixed
  Val3=2d
  Lbl3=Zero Pad
[END]
[BEGIN]
  ObjTp=Dp
  H=4
  Tp=1
  SD=The length of the *value* part of the string
  HD=True
  DV=5d
  Sgn=0
  Lng=False
  NF=1
  NoS=True
  DNF=1
  VVS=1
  LR=1d
  HR=5d
[END]
[BEGIN]
  ObjTp=Dp
  H=5
  Tp=1
  SD=The number of decimal places (valid for Decimal ONLY)
  HD=True
  DV=0d
  Sgn=0
  Lng=False
  NF=1
  NoS=True
  DNF=1
  VVS=1
  LR=0d
  HR=5d
[END]
[BEGIN]
  ObjTp=Dp
  H=6
  Tp=1
  SD=A string to add to the beginning or end of the value string
  HD=True
  DV=
  NoS=False
  VVS=0
[END]
[BEGIN]
  ObjTp=Dp
  H=7
  Tp=1
  SD=A string to add to the beginning or end of the value string
  HD=True
  DV=
  NoS=False
  VVS=0
[END]
